spring:
  datasource:
    url: jdbc:mysql://112.74.179.40/medical?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: windflytest
    password: Jif_123_cn
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    content-type: text/html
    mode: HTML5
    cache: false
  http:
    multipart:
      max-file-size: 10Mb
      max-request-size: 100Mb
  mail:
    host: smtp.qq.com
    username: 865023702@qq.com
    password: kvxtbamhhfivbfaj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    default-encoding: UTF-8
  redis:
    database: 0
    host: 112.74.179.40
    port: 6379
    password: Jif_123_cn
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 10
      min-idle: 0
    timeout: 0



server:
  context-path: /
  port: 80

mybatis:
  mapper-locations: classpath:mappering/*.xml


pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql





